import RPi.GPIO as rg
import time

rg.setwarnings(False)
rg.cleanup()
rg.setmode(rg.BCM)
rg.setup(6, rg.OUT)
rg.setup(7, rg.OUT)
rg.setup(8, rg.OUT)
rg.setup(9, rg.OUT)
rg.setup(10, rg.OUT)
rg.setup(12, rg.OUT)
rg.setup(13, rg.OUT)
rg.setup(16, rg.OUT)
rg.setup(17, rg.OUT)
rg.setup(18, rg.OUT)
rg.setup(19, rg.OUT)
rg.setup(20, rg.OUT)

rg.output(6, False)
rg.output(8, False)
rg.output(18, False)
rg.output(20, False)
rg.output(7, False)
rg.output(9, False)
rg.output(10, False)
rg.output(12, False)
rg.output(13, False)
rg.output(16, False)
rg.output(17, False)
rg.output(19, False)

while True :

    rg.output(6, True)
    rg.output(8, False)
    rg.output(18, True)
    rg.output(20, True)
    rg.output(7, False)
    rg.output(9, False)
    rg.output(17, False)
    rg.output(19, True)
    rg.output(10, False)
    rg.output(13, False)
    rg.output(12, False)

    time.sleep(5)
    rg.output(6, False)
    rg.output(8, False)
    rg.output(18, False)
    rg.output(20, True)
    rg.output(7, True)
    rg.output(9, False)
    rg.output(17, True)
    rg.output(19, True)
    rg.output(10, False)
    rg.output(13, False)
    rg.output(12, False)

    time.sleep(5)
    rg.output(6, False)
    rg.output(8, True)
    rg.output(12, False)
    rg.output(16, False)
    rg.output(7, False)
    rg.output(9, False)
    rg.output(17, True)
    rg.output(19, False)
    rg.output(10, False)
    rg.output(13, False)
    rg.output(18, True)
    rg.output(20, True)

    time.sleep(5)
    rg.output(6, False)
    rg.output(8, False)
    rg.output(18, True)
    rg.output(20, False)
    rg.output(7, False)
    rg.output(9, True)
    rg.output(17, True)
    rg.output(19, True)
    rg.output(10, False)
    rg.output(13, False)
    rg.output(12, False)

    time.sleep(2)
rg.cleanup()


