#include<bits/stdc++.h>
using namespace std;

int main() {
	int p, q;
	
	p = 9;
	q = 4;
	cout << "The value of p : " << p << "\n";
	cout << "The value of q : " << q << "\n";
	
	int a, b;
	cout << "Enter a value randomly thought by Alice : ";
	cin >> a;
	cout << "Enter a value randomly thought by Bob : ";
	cin >> b;
	
	int ka, kb;
	ka = (int)pow(q, a) % p;
	kb = (int)pow(q, b) % p;
	
	cout << "Key generated by Alice : " << ka << "\n";
	cout << "Key generated by Bob : " << kb << "\n";
	
	cout << "After performing key-exchange...\n";
	
	int fa, fb;
	fa = (int)pow(q, kb) % p;
	fb = (int)pow(q, ka) % p;
	
	cout << "Final value with Alice : " << fa << "\n";
	cout << "Final value with Bob : " << fa << "\n"; 
	
	if(fa == fb) {
		cout << "Key exchange was successful\n";
	}
	else {
		cout << "Key exchange failed\n";
	}
}
