/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class operation */

#ifndef _Included_operation
#define _Included_operation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     operation
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_operation_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     operation
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_operation_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     operation
 * Method:    mult
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_operation_mult
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     operation
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_operation_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
